### ISSUE TITLE
parent pulls in jdom-2.0.5 which leads to defunct XML parsing

### ISSUE THREAD

**Issue by axtimwalde** [bigdataviewer/pom-bigdataviewer#2]
Needs jdom-2.0.6 which comes with pom-scijava-8.4.0

Fixed with commit https://github.com/bigdataviewer/pom-bigdataviewer/commit/afff23f1cb0f59e3f37d10848e18b301ccdaa934

We should make a release 2.2.2 soon

**Comment by tpietzsch** [comment]
ok, I released it.

**Comment by axtimwalde** [comment]
Thanks!
